
SELECT CONVERT(VARCHAR, GETDATE(), 101) /*MM,DD,AA*/

SELECT CONVERT(VARCHAR, GETDATE(), 113)

SELECT CONVERT(VARCHAR, GETDATE(), 130)

SELECT CONVERT(decimal(10,5), 193.57)/*CONVERTER EM DECIMAL DE 5 CASAS DECIMAIS*/

SELECT * FROM [TABELA DE PRODUTOS]

SELECT 'O preço do produto ' + [NOME DO PRODUTO] + ' é ' +  [PREÇO DE LISTA] 
from [TABELA DE PRODUTOS]

SELECT 'O preço do produto ' + [NOME DO PRODUTO] + ' é ' +  CONVERT(VARCHAR, [PREÇO DE LISTA]) 
from [TABELA DE PRODUTOS]

/*Queremos construir um SQL cujo resultado seja, para cada cliente: **"O cliente João da Silva faturou 
120000 no ano de 2016". Somente para o ano de 2016.*/

SELECT * FROM [dbo].[NOTAS FISCAIS]
SELECT * FROM  [dbo].[ITENS NOTAS FISCAIS]
SELECT * FROM [dbo].[TABELA DE CLIENTES]

SELECT 'O Cliente ' + [NOME] + ' faturou ' + CONVERT(VARCHAR, ([QUANTIDADE]*[PREÇO])) + ' no ano de ' + 
CONVERT(VARCHAR, YEAR (DATA)) AS SENTENCA FROM [dbo].[NOTAS FISCAIS]
INNER JOIN [dbo].[ITENS NOTAS FISCAIS] ON [dbo].[ITENS NOTAS FISCAIS].NUMERO = [dbo].[NOTAS FISCAIS].NUMERO
INNER JOIN [dbo].[TABELA DE CLIENTES] ON [dbo].[TABELA DE CLIENTES].CPF = [dbo].[NOTAS FISCAIS].CPF
WHERE YEAR(DATA) = 2016

