/*O meu cliente pediu para que mostrasse um relatório mostrando, no ano de 2016, e somente no ano de 
2016, qual foi o meu faturamento em dinheiro, em grana, por sabor de produto e eu quero ver a 
participação daquela venda em relação ao total.*/

/*primeiro eu preciso ter a venda dos meus produtos por sabor no ano de 2016*/
SELECT *FROM [dbo].[TABELA DE PRODUTOS] 
SELECT* FROM [dbo].[NOTAS FISCAIS] 
SELECT * FROM [dbo].[ITENS NOTAS FISCAIS]

/* SELEÇAO 1 PARA EXEMPLIFICAR OS CAMPOS DESEJADOS*/
SELECT TP.SABOR FROM [dbo].[TABELA DE PRODUTOS] TP
SELECT NF.DATA FROM [dbo].[NOTAS FISCAIS] NF
SELECT (INF.PREÇO * INF.QUANTIDADE) AS FATURAMENTO FROM [dbo].[ITENS NOTAS FISCAIS] INF


/* CRIANDO A TABELA COM FATURAMENTO*/
SELECT TP.SABOR, NF.DATA , (INF.PREÇO * INF.QUANTIDADE) AS FATURAMENTO 
FROM [dbo].[TABELA DE PRODUTOS] TP
INNER JOIN [dbo].[ITENS NOTAS FISCAIS] INF 
ON TP.[CODIGO DO PRODUTO] = INF.[CODIGO DO PRODUTO]
INNER JOIN [dbo].[NOTAS FISCAIS] NF
ON NF.NUMERO = INF.NUMERO

/*SELECIONANDO O ANO*/
SELECT TP.SABOR, YEAR( NF.DATA ) AS ANO, (INF.PREÇO * INF.QUANTIDADE) AS FATURAMENTO 
FROM [dbo].[TABELA DE PRODUTOS] TP
INNER JOIN [dbo].[ITENS NOTAS FISCAIS] INF 
ON TP.[CODIGO DO PRODUTO] = INF.[CODIGO DO PRODUTO]
INNER JOIN [dbo].[NOTAS FISCAIS] NF
ON NF.NUMERO = INF.NUMERO

/* SOMA DO FATURAMENTO POR ANO*/
SELECT TP.SABOR, YEAR( NF.DATA ) AS ANO, SUM (INF.PREÇO * INF.QUANTIDADE) AS FATURAMENTO 
FROM [dbo].[TABELA DE PRODUTOS] TP
INNER JOIN [dbo].[ITENS NOTAS FISCAIS] INF 
ON TP.[CODIGO DO PRODUTO] = INF.[CODIGO DO PRODUTO]
INNER JOIN [dbo].[NOTAS FISCAIS] NF
ON NF.NUMERO = INF.NUMERO
GROUP BY TP.SABOR, YEAR( NF.DATA )


/* SOMA DO FATURAMENTO POR ANO PARA 2016*/
SELECT TP.SABOR, YEAR( NF.DATA ) AS ANO, SUM (INF.PREÇO * INF.QUANTIDADE) AS FATURAMENTO 
FROM [dbo].[TABELA DE PRODUTOS] TP
INNER JOIN [dbo].[ITENS NOTAS FISCAIS] INF 
ON TP.[CODIGO DO PRODUTO] = INF.[CODIGO DO PRODUTO]
INNER JOIN [dbo].[NOTAS FISCAIS] NF
ON NF.NUMERO = INF.NUMERO
WHERE YEAR( NF.DATA ) = 2016
GROUP BY TP.SABOR, YEAR( NF.DATA )

/*Eu agora preciso, para calcular aqui o meu percentual, eu preciso fazer uma divisão entre a venda que 
eu fiz no ano com o total das vendas. */

/*FATURAMENTO DO ANO DE 2016*/
SELECT  YEAR( NF.DATA ) AS ANO, SUM (INF.PREÇO * INF.QUANTIDADE) AS TOTAL 
FROM [dbo].[TABELA DE PRODUTOS] TP
INNER JOIN [dbo].[ITENS NOTAS FISCAIS] INF 
ON TP.[CODIGO DO PRODUTO] = INF.[CODIGO DO PRODUTO]
INNER JOIN [dbo].[NOTAS FISCAIS] NF
ON NF.NUMERO = INF.NUMERO
WHERE YEAR( NF.DATA ) = 2016
GROUP BY  YEAR( NF.DATA )

/*TRAZERNDO O TOTAL PARA A TABELA DE FATURAMENTO*/

SELECT AUX1.SABOR, AUX1.ANO, AUX1.FATURAMENTO, AUX2.TOTAL
FROM
(SELECT TP.SABOR, YEAR( NF.DATA ) AS ANO, SUM (INF.PREÇO * INF.QUANTIDADE) AS FATURAMENTO 
FROM [dbo].[TABELA DE PRODUTOS] TP
INNER JOIN [dbo].[ITENS NOTAS FISCAIS] INF 
ON TP.[CODIGO DO PRODUTO] = INF.[CODIGO DO PRODUTO]
INNER JOIN [dbo].[NOTAS FISCAIS] NF
ON NF.NUMERO = INF.NUMERO
GROUP BY TP.SABOR, YEAR( NF.DATA )) AUX1
INNER JOIN
(SELECT  YEAR( NF.DATA ) AS ANO, SUM (INF.PREÇO * INF.QUANTIDADE) AS TOTAL 
FROM [dbo].[TABELA DE PRODUTOS] TP
INNER JOIN [dbo].[ITENS NOTAS FISCAIS] INF 
ON TP.[CODIGO DO PRODUTO] = INF.[CODIGO DO PRODUTO]
INNER JOIN [dbo].[NOTAS FISCAIS] NF
ON NF.NUMERO = INF.NUMERO
WHERE YEAR( NF.DATA ) = 2016
GROUP BY  YEAR( NF.DATA )) AUX2
ON AUX1.ANO = AUX2.ANO

/*PERCENTUAL DE PARTICIPACAO*/
SELECT AUX1.SABOR, AUX1.ANO, AUX1.FATURAMENTO, (AUX1.FATURAMENTO /AUX2.TOTAL) *100 AS PERCENTUAL
FROM
(SELECT TP.SABOR, YEAR( NF.DATA ) AS ANO, SUM (INF.PREÇO * INF.QUANTIDADE) AS FATURAMENTO 
FROM [dbo].[TABELA DE PRODUTOS] TP
INNER JOIN [dbo].[ITENS NOTAS FISCAIS] INF 
ON TP.[CODIGO DO PRODUTO] = INF.[CODIGO DO PRODUTO]
INNER JOIN [dbo].[NOTAS FISCAIS] NF
ON NF.NUMERO = INF.NUMERO
GROUP BY TP.SABOR, YEAR( NF.DATA )) AUX1
INNER JOIN
(SELECT  YEAR( NF.DATA ) AS ANO, SUM (INF.PREÇO * INF.QUANTIDADE) AS TOTAL 
FROM [dbo].[TABELA DE PRODUTOS] TP
INNER JOIN [dbo].[ITENS NOTAS FISCAIS] INF 
ON TP.[CODIGO DO PRODUTO] = INF.[CODIGO DO PRODUTO]
INNER JOIN [dbo].[NOTAS FISCAIS] NF
ON NF.NUMERO = INF.NUMERO
WHERE YEAR( NF.DATA ) = 2016
GROUP BY  YEAR( NF.DATA )) AUX2
ON AUX1.ANO = AUX2.ANO

/*ORDENANDO PELO FATURAMENTO*/
SELECT AUX1.SABOR, AUX1.ANO, AUX1.FATURAMENTO, (AUX1.FATURAMENTO /AUX2.TOTAL) *100 AS PERCENTUAL
FROM
(SELECT TP.SABOR, YEAR( NF.DATA ) AS ANO, SUM (INF.PREÇO * INF.QUANTIDADE) AS FATURAMENTO 
FROM [dbo].[TABELA DE PRODUTOS] TP
INNER JOIN [dbo].[ITENS NOTAS FISCAIS] INF 
ON TP.[CODIGO DO PRODUTO] = INF.[CODIGO DO PRODUTO]
INNER JOIN [dbo].[NOTAS FISCAIS] NF
ON NF.NUMERO = INF.NUMERO
GROUP BY TP.SABOR, YEAR( NF.DATA )) AUX1
INNER JOIN
(SELECT  YEAR( NF.DATA ) AS ANO, SUM (INF.PREÇO * INF.QUANTIDADE) AS TOTAL 
FROM [dbo].[TABELA DE PRODUTOS] TP
INNER JOIN [dbo].[ITENS NOTAS FISCAIS] INF 
ON TP.[CODIGO DO PRODUTO] = INF.[CODIGO DO PRODUTO]
INNER JOIN [dbo].[NOTAS FISCAIS] NF
ON NF.NUMERO = INF.NUMERO
WHERE YEAR( NF.DATA ) = 2016
GROUP BY  YEAR( NF.DATA )) AUX2
ON AUX1.ANO = AUX2.ANO
ORDER BY AUX1.FATURAMENTO DESC

/*AJUSTES FINAIS*/
SELECT AUX1.SABOR, AUX1.ANO, CONVERT(DECIMAL( 15,2), AUX1.FATURAMENTO) AS FATURAMENTO,
CONVERT(varchar, CONVERT(DECIMAL(15,2), (AUX1.FATURAMENTO /AUX2.TOTAL) *100)) + '%' AS PERCENTUAL
FROM
(SELECT TP.SABOR, YEAR( NF.DATA ) AS ANO, SUM (INF.PREÇO * INF.QUANTIDADE) AS FATURAMENTO 
FROM [dbo].[TABELA DE PRODUTOS] TP
INNER JOIN [dbo].[ITENS NOTAS FISCAIS] INF 
ON TP.[CODIGO DO PRODUTO] = INF.[CODIGO DO PRODUTO]
INNER JOIN [dbo].[NOTAS FISCAIS] NF
ON NF.NUMERO = INF.NUMERO
GROUP BY TP.SABOR, YEAR( NF.DATA )) AUX1
INNER JOIN
(SELECT  YEAR( NF.DATA ) AS ANO, SUM (INF.PREÇO * INF.QUANTIDADE) AS TOTAL 
FROM [dbo].[TABELA DE PRODUTOS] TP
INNER JOIN [dbo].[ITENS NOTAS FISCAIS] INF 
ON TP.[CODIGO DO PRODUTO] = INF.[CODIGO DO PRODUTO]
INNER JOIN [dbo].[NOTAS FISCAIS] NF
ON NF.NUMERO = INF.NUMERO
WHERE YEAR( NF.DATA ) = 2016
GROUP BY  YEAR( NF.DATA )) AUX2
ON AUX1.ANO = AUX2.ANO
ORDER BY AUX1.FATURAMENTO DESC

/*Modifique o relatório, mas agora para ver o ranking das vendas por tamanho.*/

SELECT AUX1.TAMANHO, AUX1.ANO, CONVERT(DECIMAL( 15,2), AUX1.FATURAMENTO) AS FATURAMENTO,
CONVERT(varchar, CONVERT(DECIMAL(15,2), (AUX1.FATURAMENTO /AUX2.TOTAL) *100)) + '%' AS PERCENTUAL
FROM
(SELECT TP.TAMANHO, YEAR( NF.DATA ) AS ANO, SUM (INF.PREÇO * INF.QUANTIDADE) AS FATURAMENTO 
FROM [dbo].[TABELA DE PRODUTOS] TP
INNER JOIN [dbo].[ITENS NOTAS FISCAIS] INF 
ON TP.[CODIGO DO PRODUTO] = INF.[CODIGO DO PRODUTO]
INNER JOIN [dbo].[NOTAS FISCAIS] NF
ON NF.NUMERO = INF.NUMERO
GROUP BY TP.TAMANHO, YEAR( NF.DATA )) AUX1
INNER JOIN
(SELECT  YEAR( NF.DATA ) AS ANO, SUM (INF.PREÇO * INF.QUANTIDADE) AS TOTAL 
FROM [dbo].[TABELA DE PRODUTOS] TP
INNER JOIN [dbo].[ITENS NOTAS FISCAIS] INF 
ON TP.[CODIGO DO PRODUTO] = INF.[CODIGO DO PRODUTO]
INNER JOIN [dbo].[NOTAS FISCAIS] NF
ON NF.NUMERO = INF.NUMERO
WHERE YEAR( NF.DATA ) = 2016
GROUP BY  YEAR( NF.DATA )) AUX2
ON AUX1.ANO = AUX2.ANO
ORDER BY AUX1.FATURAMENTO DESC
