
SELECT NOME, BAIRRO FROM [TABELA DE CLIENTES]

/* selecionar o nome e bairro da tabela de clientes, onde o bairro coencidam na tabela de vendedores*/
SELECT NOME, BAIRRO FROM [TABELA DE CLIENTES]
WHERE BAIRRO IN (SELECT BAIRRO FROM [TABELA DE VENDEDORES])

/* selecionar o valor máximo do preço de lista da tabela de produtos*/
SELECT EMBALAGEM, MAX([PREÇO DE LISTA]) AS MAX_PRECO  FROM [TABELA DE PRODUTOS] GROUP BY EMBALAGEM
SELECT EMBALAGEM, MAX([PREÇO DE LISTA])  FROM [TABELA DE PRODUTOS] GROUP BY EMBALAGEM

/* selecionar o valor máximo do preço de lista da tabela de produtos "NOVA_CONSULTA" menor que 5*/
SELECT NOVA_CONSULTA.EMBALAGEM, NOVA_CONSULTA.MAX_PRECO
FROM (SELECT EMBALAGEM, MAX([PREÇO DE LISTA]) AS MAX_PRECO FROM [TABELA DE PRODUTOS] GROUP BY EMBALAGEM)
NOVA_CONSULTA
WHERE NOVA_CONSULTA.MAX_PRECO <= 5

/*Qual seria a consulta, usando sub-consulta, que seria equivalente a:*/
SELECT CPF, COUNT(*) FROM [NOTAS FISCAIS]
WHERE YEAR(DATA) = 2016
GROUP BY CPF
HAVING COUNT(*) > 2000

/*RESPOSTA*/
SELECT NOVA_CONSULTA.CPF, NOVA_CONSULTA.CONTAGEM FROM
(SELECT CPF, COUNT(*) AS CONTAGEM FROM [NOTAS FISCAIS] WHERE YEAR(DATA) = 2016 GROUP BY CPF) 
NOVA_CONSULTA
WHERE NOVA_CONSULTA.CONTAGEM > 2000